### PR TITLE
Various Updates and fixes 

### PR DESCRIPTION
**Pull request by BriceShatzer**
-  fixes twitter link
- creates "SDK" page 
- various styling tweaks 

All work can be previewed [here](http://briceshatzer.com/paypal.github.com/)

### CODE REVIEW

**Comment by BriceShatzer** [comment]
hey @mstuart, absurdly low priority but, do happen to have the ability to give me write access to this repo?

**Comment by mstuart** [comment]
nice!!! :D looks good 👍 

I see the preview link goes to the old page (without mentions of react-paypal-js, etc). 

Is there another link to preview the changes in this PR?

**Comment by BriceShatzer** [comment]
The SDKs are all on a [different page](http://briceshatzer.com/paypal.github.com/sdk) which you can get to by the link in the upper right corner. Do you want me to figure out a way incorporate them (or at least the active ones) onto that main page?

**Comment by mstuart** [comment]
I think it's good as it is for now 👍  As a follow-up, let's chat w/ the Web Platform team to see which of those repos on the front-page are dead or unmaintained. I have a feeling most of them are.

**Pull request merged**
